name: MineQuest
main: com.theminequest.MineQuest.MineQuest
version: ${build.number}

author: JMonk
authors: [Echobob, Xu_R, Ltan, Makraiz, Blaksmith]

description: This plugin, and its add-ons expands Minecraft to add in Npcs, Quests, and custom events to create a Role-Play enviorment in Minecraft
website: www.theminequest.com

load: POSTWORLD
loadbefore: [Minequest-NPC, Minequest-Spells, Minequest-spout]

depend: [Vault]

commands:
	minequest: 
		permission: minequest.user
	class:
		aliases: mqclass
		permission: minequest.user	
	quest:
		aliases: mqquest
		permission: minequest.user
	spell:
		aliases: mqspell
		permission: minequest.user
	npc:
		aliases: mqnpc
		permission: minequest.user
	char:
		aliases: mqchar
		permission: minequest.user
		
permissions:
	minequest.*:
		description: Access to all Minequest-Core commands
		children:
			minequest.user:true
			minequest.op:true
	minequest.user:
		default: true
	minequest:
		default: op		
		children:
			minequest.user:true