name: MineQuest
main: com.theminequest.MineQuest.MineQuest
version: ${build.version}

author: JMonk
authors: [Echobob, Xu_R, phrstbrn, Ltan, Makraiz, Blaksmith]

description: This plugin, and its add-ons expands Minecraft to add in Npcs, Quests, and custom events to create a Role-Play enviorment in Minecraft
website: www.theminequest.com

load: POSTWORLD
loadbefore: [MineQuest-NPC, MineQuest-RPG, MineQuest-Events, MineQuest-Abilities, MineQuest-Spout]

softdepend: [Vault]

commands:
  minequest:
    description: View MineQuest commands.
  quest:
    description: View Quest commands.
    aliases: [mqquest,mquest]
    permission: minequest.quest
  party:
    description: View Party commands.
    aliases: [mqparty,questparty]
    permission: minequest.party
    
permissions:
  minequest.*:
    description: Allows all MineQuest-Core commands.
    default: op
    children:
      minequest.quest: true
      minequest.party: true
  minequest.quest:
    description: Allows MQ-Core quest-related commands.
    default: true
  minequest.party:
    description: Allows MQ-Core party-related commands.
    default: true