name: MineQuest
main: com.theminequest.MineQuest.MineQuest
version: ${build.number}
author: Monk
authors: [Echobob, Ltan, makraiz, Blaksmith]
description: This plugin expands minecraft to add in Npcs, Quests, and custom events to create a Role-Play enviorment in Minecraft

softdepend: [Vault]
