name: MineQuest
main: com.theminequest.MineQuest.MineQuest
version: ${build.number}

author: JMonk
authors: [Echobob, Xu_R, Ltan, Makraiz, Blaksmith]

description: This plugin, and its add-ons expands Minecraft to add in Npcs, Quests, and custom events to create a Role-Play enviorment in Minecraft
website: www.theminequest.com

load: POSTWORLD
loadbefore: [MineQuest-NPC, MineQuest-RPG, MineQuest-Events, MineQuest-Abilities, MineQuest-Spout]

depend: [Vault]

commands:
  minequest:
    description: View MineQuest commands.
    permission: minequest.user
  quest:
    description: View Quest commands.
    aliases: [mqquest]
    permission: minequest.user
  party:
    description: View Party commands.
    aliases: [mqparty]
    permission: minequest.user
    
permissions:
  minequest.*:
    description: Allows all MineQuest-1-Core commands.
    children:
      minequest.user: true
      minequest.op: true
  minequest.user:
    description: Allows MQ-1-Core user-related commands.
    default: true
  minequest.op:
    description: Allows MQ-1-Core administrator-related commands.
    default: op
    children:
      minequest.user: true